#!/bin/bash
#SBATCH --job-name=T2_3    # The name of the job
#SBATCH --partition=xeon     # The main partition of miniHPC
#SBATCH --hint=nomultithread # Disable hardware multithreading
#SBATCH --exclusive          # Exclusive access to resources
#SBATCH --time=00:10:00      # Requested execution time
#SBATCH --nodes=4            # Requested number of nodes
#SBATCH --ntasks-per-node=2  # Requested processes per node
#SBATCH --cpus-per-task=1    # Requested threads per process
#SBATCH --output=T2_3.out

# Tell Slurm to execute something (e.g. your code)
# We execute the hostname command as a placeholder
module load OpenMPI/5.0.3-GCC-13.3.0
mpicc -O3 T2.c -o T2
mpirun ./T2